name: "Junit Report to Annotations"
description: "Create an annotation of the test run summary and also list first n failed tests as separate annotations"
branding:
  icon: "box"
  color: "green"
inputs:
  access-token:
    description: "github token"
    required: true
  path:
    description: "glob to junit xml files"
    required: true
    default: "**/TEST-*.xml"
  includeSummary:
    description: "include summary annotation"
    required: true
    default: true
  numFailures:
    description: "max number of failed tests to include"
    require: true
    default: 10
  name:
    description: "Name of the Check in the github actions UI"
    require: true
    default: "Junit Results"
outputs:
  summary:
    description: "The test run summary"
runs:
  using: "node16"
  main: "index.js"
